revisited

diff --git a/install b/install
--- a/install
+++ b/install
@@ -365,7 +365,7 @@ unship()
 
 update()
 {
-  test ! ${isUpdate} && return
+  test ! ${update_arg} && return
 
   local prj
 
@@ -373,21 +373,21 @@ update()
   declare -a prjs
   prjs=( $* )
 
-  if [ ${isUpdate} ] && [ ${w_perm} ] ; then
-    if [ "${isUpdate/QA/}" != "${isUpdate}" ] ; then
+  if [ ${update_arg} ] && [ ${w_perm} ] ; then
+    if [ "${update_arg/QA/}" != "${update_arg}" ] ; then
       if [ -d ${QA_SRC}/.git ] ; then
          update_QA_SRC
       fi
     fi
   fi
 
-  if [ ${isUpdate} != QA ] ; then
-     # now for project related tables and programs
-     for prj in $* ; do
-        update_external $prj ${isUpdate:+--update=${isUpdate}} \
-           ${w_perm:+--no-w-perm}
-     done
-  fi
+#  if [ ${update_arg} != QA ] ; then
+#     # now for project related tables and programs
+#     for prj in $* ; do
+#        update_external $prj ${update_arg:+--update=${update_arg}} \
+#           ${w_perm:+--no-w-perm}
+#     done
+#  fi
 
   return 0
 }
@@ -595,7 +595,7 @@ do
           : # previously set
         elif [ "${OPTNAME}" = FORCE ] ; then
           isForce=t
-          isUpdate="${isUpdate:+${isUpdate},}force"
+          update_arg="${update_arg:+${update_arg},}force"
         elif [ "${OPTNAME}" = HELP ] ; then
           descript
           exit 41
@@ -629,7 +629,7 @@ do
           exit 0
         elif [ "${OPTNAME:0:2}" = UP ] ; then
           test "${OPTVAL}" = t && OPTVAL=tables
-          isUpdate="${isUpdate:+${isUpdate},}${OPTVAL}"
+          update_arg="${update_arg:+${update_arg},}${OPTVAL}"
         elif [ "${OPTNAME}" = WORK ] ; then
           : # previously set
         elif [ "${OPTNAME}" = HDF5 ] ; then
@@ -701,11 +701,28 @@ if [ ! ${isCondaBuild} ] ; then
 fi
 
 # check correct settings in HOME/.qa-dkrz/config.txt depending on projects
-. ${QA_SRC}/scripts/check_configuration \
-      ${isForce:+--force} ${projects[*]}
-
 if [ ! ${isCondaBuild} ] && [ ! ${isBuild} ] ; then
+   . ${QA_SRC}/scripts/check_configuration \
+      ${isForce:+--force} ${update_arg:+--up=${update_arg}} ${projects[*]}
+
    update ${projects[*]}
+
+   if [ -f $HOME/.qa-dkrz/config.txt ] ; then
+     if [ -f $QA_SRC/.qa-dkrz/config.txt ] ; then
+       local md5_0 md5_1
+       md5_0=$( md5sum ${QA_SRC}/.qa-dkrz/config.txt | awk '{print $1}' )
+       md5_1=$( md5sum ${HOME}/.qa-dkrz/config.txt | awk '{print $1}' )
+       test ${md5_0} != ${md5_1} &&
+          cp ${HOME}/.qa-dkrz/config.txt ${QA_SRC}/.qa-dkrz
+     else
+        if ! mkdir -p ${QA_SRC}/.qa-dkrz 2> /dev/null ; then
+           echo "could not mkdir ${QA_SRC}/.qa-dkrz; missing permission?"
+           exit 41
+        fi
+
+        cp ${HOME}/.qa-dkrz/config.txt ${QA_SRC}/.qa-dkrz
+     fi
+   fi
 fi
 
 if [ ${isShip} ] ; then
diff --git a/scripts/getTablesPath b/scripts/getTablesPath
--- a/scripts/getTablesPath
+++ b/scripts/getTablesPath
@@ -13,30 +13,30 @@ getTablesPath_()
      return 0
   fi
 
-  local p_tables
+  local p_def_tables
 
   if try_other_sections ; then
-     QA_TABLES=$p_tables
+     QA_TABLES=$p_def_tables # set in the fct
   else
-     p_tables=${HOME}/.qa-dkrz/QA_TABLES
+     p_def_tables=${HOME}/.qa-dkrz/QA_TABLES
 
      local i
      while : ; do
         echo -e -n "\nPlease, specify a new spot for project tables "
-        read -p "[default: ${p_tables}], <cancel>: " QA_TABLES
+        read -p "[default: ${p_def_tables}], <cancel>: " QA_TABLES
+
+        case $quest in
+          ( '' ) QA_TABLES=$p_def_tables  ;;
+          c) exit 41 ;;
+          *) continue ;;
+        esac
 
         if mkdir -p ${QA_TABLES} &> /dev/null ; then
            break
         fi
 
-        echo "Could not mkdir ${QA_TABLES} (missing permission?)."
-        echo "Note that you need permissions because external table will be downloaded."
-
-        i=$(( i + 1 ))
-        if [ ${i} = 3 ] ; then
-          echo "Sorry, too many attempts. Exit"
-          exit 41
-        fi
+        echo "could not mkdir ${QA_TABLES} (missing write permission?);"
+        echo "permissions are required for downloading external tables."
      done
   fi
 
@@ -119,7 +119,7 @@ try_other_sections()
 
   fi
 
-  p_tables="${qts[ix]}"
+  p_def_tables="${qts[ix]}"
 
   return 0
 }
